cd ../resources
mv assets mods
cd ../java
FILES=`find -type f`
simple_replace "buildcraft\\.core\\.fluids\\.FluidUtils" "buildcraft.core.liquids.LiquidUtils"
simple_replace "RefineryRecipes" "RefineryRecipe"
simple_replace "RefineryRecipe\\.Recipe" "RefineryRecipe"
simple_replace "isFluidEqual" "isLiquidEqual"
simple_replace "manageFluids" "manageLiquids"
simple_replace "pipeFluids" "pipeLiquids"
simple_replace "FluidUtils" "LiquidUtils"
simple_replace "IFluidBlock" "ILiquid"
simple_replace "FluidContainerRegistry" "LiquidContainerRegistry"
simple_replace "IFluidHandler" "ITankContainer"
simple_replace "import +buildcraft\\.api\\.power\\.PowerHandler\\.Type *; *\n" ""
simple_replace "import +buildcraft\\.api\\.power\\.PowerHandler\\.PowerReceiver *; *\n" ""
simple_replace "PowerHandler" "IPowerProvider"
simple_replace "\\. *getPowerReceiver *\\( *\\) *" ""
simple_replace "FluidTankInfo" "LiquidTank"
simple_replace "(PowerHandler\\.|)PowerReceiver" "IPowerProvider"
simple_replace "getIPowerProvider" "getPowerProvider"
method_declaration IPowerProvider IPowerProvider getPowerProvider getPowerProvider ForgeDirection @SKIP@
method_declaration void void doWork doWork IPowerProvider @SKIP@
method_declaration "LiquidTank\\[\\]" "ILiquidTank\\[\\]" getTankInfo getTanks ForgeDirection ForgeDirection
simple_replace "net\\.minecraft\\.client\\.resources\\.I18n" "net.minecraft.util.StatCollector"
simple_replace "I18n\\.getString" "StatCollector.translateToLocal"
simple_replace "FluidRenderer\\.setColorForFluidStack *\\([^\\(\\),]+\\) *;? *" ""
simple_replace "net\\.minecraftforge\\.fluids" "net\\.minecraftforge\\.liquids"
simple_replace "FluidRenderer" "LiquidRenderer"
simple_replace "getFluidDisplayLists" "getLiquidDisplayLists"
simple_replace "getFluidSheet" "getLiquidSheet"
simple_replace "FluidStack" "LiquidStack"
simple_replace "FluidRegistry" "LiquidDictionary"
simple_replace "getRegisteredFluidIDs" "getLiquids"
simple_replace "EntityLivingBase" "EntityLiving"
simple_replace "onContainerClosed" "onCraftGuiClosed"
simple_replace "Item\\.glowstone" "Item.lightStoneDust"
simple_replace "isItemValidForSlot" "isStackValidForSlot"
simple_replace "getTextureManager\\( *\\)" "renderEngine"
simple_replace "(texture\\.|)TextureManager" "RenderEngine"
simple_replace "import +net\\.minecraft\\.util\\.ResourceLocation *; *\n" ""
simple_replace "ResourceLocation" "String"
